### PR TITLE
EV10.1 hardware changes

### PR DESCRIPTION
**Pull request by BrettRegnier**
PR for issue #83

### CODE REVIEW

**Comment by fluffy** [comment]
Few things I saw but it probably still needs a more careful review 

- [ ]  snap EDA stuff seems to have leaked in on BQ21040DBVR 
- [ ] C1 and C2 look they have wrong footprint 
- [ ] C33 does not have LCSC part number but other caps of same value do 
- [ ] We should have an 'JLCPCB Part #' field for every part that has the number instead of the LCSC one 
- [ ] The EEPROM should have an identifier like U? not CR1 and footprint have really werid name 
- [ ] I wonder if a normal header would just be easier to use for test points 
- [ ] Given the placement of the test points, will the screen still fit ? 
- [ ] I think we had a bunch of changes in b ugs like add SDO and JTAG programs, reset boot buttons, move battery connector to not be so close to keyboard connector etc. They don't see to be in. 

Tried to review but a bit hard because no easy way to see what hanged. We may just need some diffs on schematic and PCB images.

**Comment by fluffy** [comment]
Can we check the circuit for the MIC and C18 and C17, R9.  It just seems off to me in that nothing pulls MiC_N to GND . 

Lets also add a 1/8 TRRS audio jack with headset.

**Comment by BrettRegnier** [comment]
> Can we check the circuit for the MIC and C18 and C17, R9. It just seems off to me in that nothing pulls MiC_N to GND .
> 
> Lets also add a 1/8 TRRS audio jack with headset.

Ok, I'll add that into EV10.1. I ran EV10.1 in the Electrical rules checker, and it has quite a few warning which may take awhile to go through. My only concern with that is EV11 (current newest) would have the same warnings and fixing them all on EV10.1 would feel like a huge time sink unless we scrap current EV11 and use EV10.1 as the base template for it.

**Comment by BrettRegnier** [comment]
Regarding JLCPCB Part #, the LCSC Part # is the first primary field, so I chose to use that field tag instead.

**Comment by BrettRegnier** [comment]
>C1 and C2 look they have wrong footprint

Should it be larger or smaller?

**Comment by fluffy** [comment]
> Regarding JLCPCB Part #, the LCSC Part # is the first primary field, so I chose to use that field tag instead.

The problem is not all the part numbers stay the same between them and we are ordering from JLCPCB so it si really weird to put JLCPCB number is a field labled LCSC. It is really easy to fix, you just open the spreadsheet tab for the board and copy them from one column to the other.

**Comment by BrettRegnier** [comment]
Closing due to a updated branch and PR #92

**Pull request closed without merging**
